beta_forcing:
  file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/carbonate-sensitivities/carbonate_sensitivity_daily.nc
  taxMode: extend
  tintalgo: linear
  varname: dDICdCO2
  year_align: 346
  year_first: 346
  year_last: 368
date: 1999-01
eta_forcing:
  file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/carbonate-sensitivities/carbonate_sensitivity_daily.nc
  taxMode: extend
  tintalgo: linear
  varname: dDICdALK
  year_align: 346
  year_first: 346
  year_last: 368
experiments:
- basin: North_Atlantic_basin
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-North_Atlantic_basin.000-1999-01.nc
  is_alk: false
  polygon: 0
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: North_Atlantic_basin
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-North_Atlantic_basin.001-1999-01.nc
  is_alk: false
  polygon: 1
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: North_Pacific_basin
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-North_Pacific_basin.000-1999-01.nc
  is_alk: false
  polygon: 0
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: North_Pacific_basin
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-North_Pacific_basin.001-1999-01.nc
  is_alk: false
  polygon: 1
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: South
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-South.000-1999-01.nc
  is_alk: false
  polygon: 0
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: South
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-South.001-1999-01.nc
  is_alk: false
  polygon: 1
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: Southern_Ocean
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-Southern_Ocean.001-1999-01.nc
  is_alk: false
  polygon: 1
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
- basin: Southern_Ocean
  forcing_file: /global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-Southern_Ocean.005-1999-01.nc
  is_alk: false
  polygon: 5
  taxMode: cycle
  tintalgo: linear
  varname: alk_forcing
  year_align: 347
  year_first: 1999
  year_last: 2019
suffix: test-dor-daily
