from rich.console import Console

console = Console()


# But loads of these data variables aren't really dependent data variables at all...
COORDS = [
    "dz",
    "dzw",
    "KMT",
    "KMU",
    "REGION_MASK",
    "UAREA",
    "TAREA",
    "HU",
    "HT",
    "DXU",
    "DYU",
    "DXT",
    "DYT",
    "HTN",
    "HTE",
    "HUS",
    "HUW",
    "time_bound",
    # everything beyond here are just like fundamental constants or conversion factors, do we actually need these?
    "ANGLE",
    "ANGLET",
    "days_in_norm_year",
    "grav",
    "omega",
    "cp_sw",
    "vonkar",
    "rho_air",
    "rho_sw",
    "rho_fw",
    "stefan_boltzmann",
    "latent_heat_vapor",
    "latent_heat_fusion",
    "latent_heat_fusion_mks",
    "ocn_ref_salinity",
    "sea_ice_salinity",
    "T0_Kelvin",
    "salt_to_ppt",
    "ppt_to_salt",
    "mass_to_Sv",
    "heat_to_PW",
    "salt_to_Svppt",
    "salt_to_mmday",
    "momentum_factor",
    "hflux_factor",
    "fwflux_factor",
    "salinity_factor",
    "sflux_factor",
    "nsurface_t",
    "nsurface_u",
    "radius",
    "sound",
    "cp_air",
    "area_m2",
]
